CREATE DATABASE IF NOT EXISTS maria CHARACTER SET utf8mb4 COLLATE utf8mb4_general-ci;
CREATE USER IF NOT EXISTS 'maria'@'%' IDENTIFIED BY '1qaz@WSX';
GRANT ALL PRIVILEGES ON maria.* TO 'maria'@'%';

FLUSH PRIVILEGES;